version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@1.2.0

workflows:
  changed-paths:
    when: << pipeline.git.branch =~ /^FEAT\/create-circleci-configuration/ >>
    jobs:
      - path-filtering/filter:
          base-revision: master
          config-path: .circleci/terraform-pipeline.yml
          mapping: |
            gcp-projects/hub-project/.* gcp-hub-project true
            gcp-projects/my-projects/.* gcp-my-projects true
