version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@1.2.0

workflows:
  changed-paths:
    jobs:
      - path-filtering/filter:
          name: Filter Changing Directories
          base-revision: master
          config-path: .circleci/terraform-pipeline.yml
          mapping: |
            gcp-projects/hub-project/.* gcp-hub-project true
            gcp-projects/my-projects/.* gcp-my-projects true
          filters:
            branches:
              only: FEAT/create-circleci-configuration
